apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app.kubernetes.io/name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: nginx
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: proxy
  name: nginx
spec:
  type: LoadBalancer 
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: tomcat

